testing:
  outputs:
    dev:
      dataset: Test
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/hirchamghermani/Desktop/Projects/dbt-hicham/keyfile.json
      location: US
      method: service-account
      priority: interactive
      project: vertical-sunset-404715
      threads: 1
      type: bigquery
  target: dev
